name: krellian-kiosk
version: '0.1'
summary: Krellian Kiosk
description: A kiosk runtime for web content
base: core18
confinement: strict
grade: devel

architectures:
  - build-on: armhf

apps:
  krellian-kiosk:
    daemon: simple
    restart-condition: always
    command: desktop-launch xwayland-kiosk-launch "$SNAP/krellian-kiosk/krellian-kiosk"  "--no-sandbox"
    environment:
      XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"
    slots: [ x11 ]
    plugs:
    - browser-sandbox
    - network
    - network-bind
    - network-manager
    - opengl
    - pulseaudio
    - wayland
    - x11-plug

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  x11-plug: # because cannot have identical plug/slot name in same yaml.
    interface: x11

parts:
  krellian-kiosk:
    plugin: nodejs
    nodejs-package-manager: npm
    nodejs-version: 12.18.2
    source: https://github.com/krellian/kiosk.git
    after: [desktop-gtk3, xwayland-kiosk-helper]
    override-build: |
        ELECTRON_GET_USE_PROXY=1 npm install
        npm install -g node-gyp
        ./node_modules/.bin/electron-rebuild
        ELECTRON_GET_USE_PROXY=1 ./node_modules/.bin/electron-packager . --overwrite --platform=linux --arch=$ARCH --output=release-build --prune=true
        cp -v -R ./krellian-kiosk-linux-$ARCH $SNAPCRAFT_PART_INSTALL/krellian-kiosk
    stage-packages:
    - libasound2
    - libgconf-2-4
    - libnss3
    - libx11-xcb1
    - libxss1
    - libxtst6
    build-packages:
    - nodejs
    - npm
    - unzip

  # Adapted from snapcraft-desktop-helpers https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml#L183
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5

  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [ build-essential ]
    stage-packages: [ xwayland, i3, libegl1-mesa, libgl1-mesa-glx ]
